export interface ProviderEmission {
  readonly path: string;
  readonly content: string;
}

const generatedNotice =
  "<!-- Generated by agentdevflow. Do not edit this file directly. -->";

export function generatedMarkdown(body: string): string {
  const normalized = body
    .replaceAll("\r\n", "\n")
    .replaceAll("\r", "\n")
    .trimEnd();
  return `${generatedNotice}\n\n${normalized}\n`;
}
