export interface ProviderEmission {
  readonly path: string;
  readonly content: string;
}

export const nativeGeneratedNotice =
  "<!-- Generated by agentdevflow. Do not edit this file directly. -->";

export function generatedMarkdown(body: string): string {
  const normalized = body
    .replaceAll("\r\n", "\n")
    .replaceAll("\r", "\n")
    .trimEnd();
  return `${nativeGeneratedNotice}\n\n${normalized}\n`;
}

export function parseGeneratedMarkdown(content: string): string | null {
  const prefix = `${nativeGeneratedNotice}\n\n`;
  if (
    !content.startsWith(prefix) ||
    !content.endsWith("\n") ||
    content.includes("\r")
  ) {
    return null;
  }
  const body = content.slice(prefix.length, -1);
  return body === body.trimEnd() ? body : null;
}
