import {
  generatedMarkdown,
  nativeProjectInstructionPaths,
  type ProviderEmission,
} from "./common.js";

export const cursorProjectInstructionsFrontmatter = [
  "---",
  "description: Agent development flow generated by agentdevflow",
  "alwaysApply: true",
  "---",
].join("\n");

export function emitCursorProjectInstructions(body: string): ProviderEmission {
  return {
    path: nativeProjectInstructionPaths.cursor,
    content: [
      cursorProjectInstructionsFrontmatter,
      "",
      generatedMarkdown(body),
    ].join("\n"),
  };
}
