import { generatedMarkdown, type ProviderEmission } from "./common.js";

export function emitCursorProjectInstructions(body: string): ProviderEmission {
  return {
    path: ".cursor/rules/agentdevflow.mdc",
    content: [
      "---",
      "description: Agent development flow generated by agentdevflow",
      "alwaysApply: true",
      "---",
      "",
      generatedMarkdown(body),
    ].join("\n"),
  };
}
