import assert from "node:assert/strict";
import test from "node:test";

import { normalizeCandidateProjectConfig } from "../../src/config/normalize-candidate.js";
import { createPrivateProjectConfigDocument } from "../../src/interface/private-project-config-document.js";
import {
  balancedCandidateConfig,
  reorderedBalancedCandidateConfig,
} from "../fixtures/config/specimens.js";

test("produces deterministic strict JSON that remains valid JSONC", () => {
  const first = createPrivateProjectConfigDocument(balancedCandidateConfig);
  const second = createPrivateProjectConfigDocument(
    reorderedBalancedCandidateConfig,
  );
  assert.equal(first.ok, true);
  assert.equal(second.ok, true);
  if (!first.ok || !second.ok) return;

  assert.equal(first.document.syntax, "strict-json-subset-of-jsonc");
  assert.equal(second.document.content, first.document.content);
  assert.equal(second.document.contentDigest, first.document.contentDigest);
  assert.equal(
    second.document.configurationDigest,
    first.document.configurationDigest,
  );
  assert.equal(first.document.content.endsWith("\n"), true);
  assert.equal(first.document.content.includes("\r"), false);
});

test("round-trips generated bytes through the existing normalizer", () => {
  const result = createPrivateProjectConfigDocument(balancedCandidateConfig);
  assert.equal(result.ok, true);
  if (!result.ok) return;

  const parsed: unknown = JSON.parse(result.document.content);
  const normalized = normalizeCandidateProjectConfig(parsed);
  assert.equal(normalized.ok, true);
  if (!normalized.ok) return;
  assert.deepEqual(normalized.config, result.document.configuration);
  assert.equal(normalized.digest, result.document.configurationDigest);
  assert.equal("digest" in (parsed as object), false);
});

test("returns existing deterministic configuration diagnostics", () => {
  const result = createPrivateProjectConfigDocument({ schemaVersion: 0 });
  assert.equal(result.ok, false);
  if (result.ok) return;
  assert.deepEqual(
    result.diagnostics.map(({ code, path }) => ({ code, path })),
    [
      { code: "MISSING_REQUIRED_FIELD", path: "$.preset" },
      { code: "MISSING_REQUIRED_FIELD", path: "$.providers" },
      { code: "MISSING_REQUIRED_FIELD", path: "$.review" },
      { code: "MISSING_REQUIRED_FIELD", path: "$.roles" },
      { code: "MISSING_REQUIRED_FIELD", path: "$.tracker" },
    ],
  );
});
